# Generated by Django 5.1.15 on 2026-02-16 21:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('summary', models.TextField(help_text='1-2 sentence description for search results.')),
                ('category', models.CharField(choices=[('getting_started', 'Getting Started'), ('store_management', 'Store Management'), ('evaluations', 'Evaluations'), ('action_tracking', 'Action Tracking'), ('ai_features', 'AI Features'), ('reports', 'Reports'), ('scheduling', 'Scheduling'), ('team', 'Team'), ('settings', 'Settings'), ('billing', 'Billing')], max_length=30)),
                ('feature_tier', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='starter', max_length=20)),
                ('app_route', models.CharField(blank=True, default='', max_length=100)),
                ('icon_name', models.CharField(blank=True, default='', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'kb_article',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeSection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anchor', models.SlugField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='HTML content for this section.')),
                ('feature_tier', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='starter', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='kb.knowledgearticle')),
            ],
            options={
                'db_table': 'kb_section',
                'ordering': ['order'],
                'unique_together': {('article', 'anchor')},
            },
        ),
    ]
