# Generated by Django 5.1.15 on 2026-02-16 22:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingLesson',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, default='', max_length=300)),
                ('content', models.TextField(blank=True, default='')),
                ('app_route', models.CharField(blank=True, default='', max_length=100)),
                ('action_label', models.CharField(blank=True, default='', max_length=100)),
                ('roles', models.CharField(blank=True, default='', help_text='Comma-separated roles this applies to. Empty = all roles.', max_length=255)),
                ('feature_tier', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='starter', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_lessons', to='kb.knowledgesection')),
            ],
            options={
                'db_table': 'kb_onboarding_lesson',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='kb.onboardinglesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kb_user_lesson_progress',
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
