# Generated by Django 5.1.15 on 2026-02-15 19:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.organization')),
            ],
            options={
                'db_table': 'walks_scoringtemplate',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight as a percentage (e.g. 25.00 for 25%)', max_digits=5)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='walks.scoringtemplate')),
            ],
            options={
                'db_table': 'walks_section',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('max_points', models.PositiveIntegerField(default=10)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='walks.section')),
            ],
            options={
                'db_table': 'walks_criterion',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Walk',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField()),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, help_text='Computed total score as a percentage.', max_digits=6, null=True)),
                ('conducted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='walks_conducted', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.organization')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walks', to='stores.store')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='walks', to='walks.scoringtemplate')),
            ],
            options={
                'db_table': 'walks_walk',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, default='')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='walks.criterion')),
                ('walk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='walks.walk')),
            ],
            options={
                'db_table': 'walks_score',
                'unique_together': {('walk', 'criterion')},
            },
        ),
    ]
