# Generated by Django 5.1.15 on 2026-02-15 20:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalkPhoto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='apps.core.storage.walk_evidence_path')),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('score', models.ForeignKey(blank=True, help_text='The specific score/criterion this photo is evidence for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='walks.score')),
                ('walk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='walks.walk')),
            ],
            options={
                'db_table': 'walks_walkphoto',
                'ordering': ['created_at'],
            },
        ),
    ]
