# Generated by Django 5.1.15 on 2026-02-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0002_walkphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='walk',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When the walk was actually started.', null=True),
        ),
    ]
