# Generated by Django 5.1.15 on 2026-02-15 20:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0003_walk_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkphoto',
            name='section',
            field=models.ForeignKey(blank=True, help_text='The section this photo belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='walks.section'),
        ),
        migrations.CreateModel(
            name='WalkSectionNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('areas_needing_attention', models.TextField(blank=True, default='', help_text='Specific areas flagged for follow-up (e.g., Shelf Maintenance).')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walk_notes', to='walks.section')),
                ('walk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_notes', to='walks.walk')),
            ],
            options={
                'db_table': 'walks_walksectionnote',
                'unique_together': {('walk', 'section')},
            },
        ),
    ]
