# Generated by Django 5.1.15 on 2026-02-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0004_walkphoto_section_walksectionnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='walk',
            name='ai_summary',
            field=models.TextField(blank=True, default='', help_text='AI-generated summary of the walk results.'),
        ),
    ]
