# Generated by Django 5.1.15 on 2026-02-16 19:06

import apps.core.storage
import apps.walks.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_membership_evaluator_role'),
        ('stores', '0006_alter_goal_organization'),
        ('walks', '0008_walkphoto_criterion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('description', models.TextField(blank=True, default='', help_text='Auto-generated from criterion + score context.')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_action_items', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_action_items', to=settings.AUTH_USER_MODEL)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='walks.criterion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.organization')),
                ('original_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_items', to='walks.walkphoto')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_action_items', to=settings.AUTH_USER_MODEL)),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='walks.score')),
                ('walk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='walks.walk')),
            ],
            options={
                'db_table': 'walks_actionitem',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionItemResponse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('action_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='walks.actionitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.organization')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_item_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'walks_actionitemresponse',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionItemPhoto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=apps.core.storage.action_item_photo_path)),
                ('ai_analysis', models.TextField(blank=True, default='')),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.organization')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='walks.actionitemresponse')),
            ],
            options={
                'db_table': 'walks_actionitemphoto',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentPrompt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. "Knives Table"', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Instructions for what to photograph.')),
                ('ai_evaluation_prompt', models.TextField(blank=True, default='', help_text='What the AI should look for when analyzing the photo.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('rating_type', models.CharField(choices=[('none', 'Photo Only'), ('three_scale', 'Good / Fair / Poor')], default='none', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.organization')),
            ],
            options={
                'db_table': 'walks_assessmentprompt',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CalendarToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(default=apps.walks.models._generate_calendar_token, max_length=48, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'walks_calendartoken',
            },
        ),
        migrations.CreateModel(
            name='EvaluationSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. "Monthly Store Walks"', max_length=255)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=10)),
                ('day_of_month', models.PositiveIntegerField(blank=True, help_text='Day of month for monthly/quarterly schedules (1-28).', null=True)),
                ('day_of_week', models.PositiveIntegerField(blank=True, help_text='Day of week for weekly/biweekly (0=Monday, 6=Sunday).', null=True)),
                ('scope', models.CharField(choices=[('organization', 'Organization-wide'), ('region', 'Region'), ('store', 'Store')], default='organization', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('next_run_date', models.DateField()),
                ('last_run_date', models.DateField(blank=True, null=True)),
                ('reminder_days_before', models.PositiveIntegerField(default=3)),
                ('assigned_evaluator', models.ForeignKey(blank=True, help_text='If null, the store manager is assigned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_schedules', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.organization')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_schedules', to='stores.region')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_schedules', to='stores.store')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_schedules', to='walks.scoringtemplate')),
            ],
            options={
                'db_table': 'walks_evaluationschedule',
                'ordering': ['next_run_date'],
            },
        ),
        migrations.CreateModel(
            name='SelfAssessment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='pending', max_length=20)),
                ('due_date', models.DateField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True, default='')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_assessments', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_assessments', to='stores.store')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'walks_selfassessment',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentSubmission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=apps.core.storage.assessment_photo_path)),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('self_rating', models.CharField(blank=True, choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='', max_length=10)),
                ('ai_analysis', models.TextField(blank=True, default='')),
                ('ai_rating', models.CharField(blank=True, choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.organization')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='walks.assessmentprompt')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='walks.selfassessment')),
            ],
            options={
                'db_table': 'walks_assessmentsubmission',
                'ordering': ['submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SelfAssessmentTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. "Monthly Photo Check"', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_assessment_templates', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.organization')),
            ],
            options={
                'db_table': 'walks_selfassessmenttemplate',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='selfassessment',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='walks.selfassessmenttemplate'),
        ),
        migrations.AddField(
            model_name='assessmentprompt',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='walks.selfassessmenttemplate'),
        ),
    ]
