# Generated by Django 5.1.15 on 2026-02-16 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0009_actionitem_actionitemresponse_actionitemphoto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='scoring_guidance',
            field=models.TextField(blank=True, default='', help_text='Specific guidance on what each score (1-5) means for this criterion.'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='sop_text',
            field=models.TextField(blank=True, default='', help_text='Rich text SOP guidance for this criterion.'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='sop_url',
            field=models.URLField(blank=True, default='', help_text='Link to external SOP document.'),
        ),
        migrations.AddField(
            model_name='walk',
            name='evaluator_signature',
            field=models.ImageField(blank=True, help_text='Evaluator drawn signature image.', null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='walk',
            name='evaluator_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walk',
            name='location_distance_meters',
            field=models.IntegerField(blank=True, help_text='Distance in meters from the store when the walk was started.', null=True),
        ),
        migrations.AddField(
            model_name='walk',
            name='location_verified',
            field=models.BooleanField(default=False, help_text='Whether the evaluator was verified to be at the store location.'),
        ),
        migrations.AddField(
            model_name='walk',
            name='manager_review_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='walk',
            name='manager_review_status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('reviewed', 'Reviewed'), ('disputed', 'Disputed')], default='pending_review', max_length=20),
        ),
        migrations.AddField(
            model_name='walk',
            name='manager_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_walks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='walk',
            name='manager_signature',
            field=models.ImageField(blank=True, help_text='Manager drawn signature image.', null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='walk',
            name='manager_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walk',
            name='start_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='GPS latitude when the walk was started.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='walk',
            name='start_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='GPS longitude when the walk was started.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='walkphoto',
            name='exif_date',
            field=models.DateTimeField(blank=True, help_text='Date extracted from photo EXIF data.', null=True),
        ),
        migrations.AddField(
            model_name='walkphoto',
            name='image_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hash of the image data for duplicate detection.', max_length=64),
        ),
        migrations.AddField(
            model_name='walkphoto',
            name='is_fresh',
            field=models.BooleanField(default=True, help_text='Whether the photo passed freshness validation (EXIF date within 24h).'),
        ),
    ]
