# Generated by Django 5.1.15 on 2026-02-16 21:31

import apps.core.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_membership_evaluator_role'),
        ('stores', '0007_store_latitude_store_longitude_store_manager_email_and_more'),
        ('walks', '0010_criterion_scoring_guidance_criterion_sop_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('overdue_evaluation', 'Overdue Evaluation'), ('unacknowledged_walk', 'Unacknowledged Walk')], max_length=25)),
                ('escalation_level', models.CharField(choices=[('reminder', 'Reminder'), ('escalated', 'Escalated'), ('critical', 'Critical')], default='reminder', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=10)),
                ('days_overdue', models.PositiveIntegerField(default=0)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.organization')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrective_actions', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrective_actions', to='stores.store')),
                ('walk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrective_actions', to='walks.walk')),
            ],
            options={
                'db_table': 'walks_correctiveaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. "Staff training needed"', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='walks.criterion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.organization')),
            ],
            options={
                'db_table': 'walks_driver',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='score',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='Root cause driver selected when score is 3 or below.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores', to='walks.driver'),
        ),
        migrations.CreateModel(
            name='SOPDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(upload_to=apps.core.storage.sop_document_path)),
                ('file_type', models.CharField(blank=True, default='', help_text='File extension (pdf, docx, txt).', max_length=10)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('extracted_text', models.TextField(blank=True, default='', help_text='Text extracted from the document for AI analysis.')),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.organization')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_sop_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'walks_sopdocument',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SOPCriterionLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_ai_suggested', models.BooleanField(default=False)),
                ('ai_confidence', models.FloatField(blank=True, help_text='AI confidence score 0-1.', null=True)),
                ('ai_reasoning', models.TextField(blank=True, default='')),
                ('is_confirmed', models.BooleanField(default=False, help_text='Admin must confirm AI suggestions before they appear to evaluators.')),
                ('relevant_excerpt', models.TextField(blank=True, default='', help_text='Relevant excerpt from the SOP document.')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sop_links', to='walks.criterion')),
                ('sop_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_links', to='walks.sopdocument')),
            ],
            options={
                'db_table': 'walks_sopcriterionlink',
                'ordering': ['-ai_confidence'],
                'unique_together': {('sop_document', 'criterion')},
            },
        ),
    ]
