# Generated by Django 5.1.15 on 2026-02-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0011_correctiveaction_driver_score_driver_sopdocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walk',
            name='qr_scanned_at',
            field=models.DateTimeField(blank=True, help_text='When the QR code was scanned.', null=True),
        ),
        migrations.AddField(
            model_name='walk',
            name='qr_verified',
            field=models.BooleanField(default=False, help_text='Whether the walk was verified via QR code scan.'),
        ),
    ]
