# Generated by Django 5.1.15 on 2026-02-17 19:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_organization_profile_fields'),
        ('stores', '0009_region_color'),
        ('walks', '0014_industrytemplate_scoringtemplate_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('icon_name', models.CharField(blank=True, default='', help_text='Icon identifier for the frontend.', max_length=50)),
                ('category', models.CharField(choices=[('standard', 'Standard'), ('branded', 'Branded'), ('specialty', 'Specialty')], default='standard', max_length=20)),
                ('industry', models.CharField(choices=[('hardware', 'Hardware / Home Improvement'), ('grocery', 'Grocery'), ('convenience', 'Convenience Store'), ('restaurant', 'Restaurant / QSR'), ('retail', 'General Retail'), ('pharmacy', 'Pharmacy'), ('automotive', 'Automotive'), ('fitness', 'Fitness / Gym'), ('hospitality', 'Hospitality / Hotel'), ('other', 'Other')], default='hardware', max_length=30)),
                ('default_structure', models.JSONField(default=dict, help_text='Default sections → criteria for this department type.')),
                ('is_active', models.BooleanField(default=True)),
                ('install_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'walks_departmenttype',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='scoringtemplate',
            name='source_template',
            field=models.ForeignKey(blank=True, help_text='The org template this was duplicated from, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='walks.scoringtemplate'),
        ),
        migrations.AlterField(
            model_name='section',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='walks.scoringtemplate'),
        ),
        migrations.AlterField(
            model_name='walk',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='walks', to='walks.scoringtemplate'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.organization')),
            ],
            options={
                'db_table': 'walks_department',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='section',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='walks.department'),
        ),
        migrations.AddField(
            model_name='walk',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Set for department evaluations (one-off, AI-scored).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='walks', to='walks.department'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('department__isnull', True), ('template__isnull', False)), models.Q(('department__isnull', False), ('template__isnull', True)), _connector='OR'), name='section_template_or_department'),
        ),
        migrations.AddConstraint(
            model_name='walk',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('department__isnull', True), ('template__isnull', False)), models.Q(('department__isnull', False), ('template__isnull', True)), _connector='OR'), name='walk_template_or_department'),
        ),
        migrations.AddField(
            model_name='department',
            name='department_type',
            field=models.ForeignKey(blank=True, help_text='The catalog entry this was installed from, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installed_departments', to='walks.departmenttype'),
        ),
    ]
