# Generated by Django 5.1.15

import apps.core.storage
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0015_departmenttype_scoringtemplate_source_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterionReferenceImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=apps.core.storage.criterion_reference_image_path)),
                ('description', models.TextField(blank=True, default='', help_text='What this image shows and what makes it ideal for this criterion.')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_images', to='walks.criterion')),
            ],
            options={
                'db_table': 'walks_criterionreferenceimage',
            },
        ),
        migrations.AddConstraint(
            model_name='criterionreferenceimage',
            constraint=models.UniqueConstraint(fields=('criterion',), name='one_reference_image_per_criterion'),
        ),
    ]
