# Generated by Django 5.1.15 on 2026-02-18 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_achievement_plan_tier'),
        ('walks', '0016_criterionreferenceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Direct store reference for manual items (when no walk exists).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='stores.store'),
        ),
        migrations.AddField(
            model_name='correctiveaction',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='criterion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='walks.criterion'),
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='walks.score'),
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='walk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='walks.walk'),
        ),
        migrations.AlterField(
            model_name='correctiveaction',
            name='action_type',
            field=models.CharField(choices=[('overdue_evaluation', 'Overdue Evaluation'), ('unacknowledged_walk', 'Unacknowledged Walk'), ('manual', 'Manual')], max_length=25),
        ),
        migrations.AlterField(
            model_name='correctiveaction',
            name='walk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corrective_actions', to='walks.walk'),
        ),
    ]
