# Generated by Django 5.1.15 on 2026-02-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0017_actionitem_is_manual_actionitem_store_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmenttype',
            name='industry',
            field=models.CharField(choices=[('hardware', 'Hardware / Home Improvement'), ('grocery', 'Grocery'), ('convenience', 'Convenience Store'), ('restaurant', 'Restaurant / QSR'), ('retail', 'General Retail'), ('pharmacy', 'Pharmacy'), ('automotive', 'Automotive'), ('fitness', 'Fitness / Gym'), ('hospitality', 'Hospitality / Hotel'), ('discount', 'Discount / Variety'), ('other', 'Other')], default='hardware', max_length=30),
        ),
        migrations.AlterField(
            model_name='industrytemplate',
            name='industry',
            field=models.CharField(choices=[('hardware', 'Hardware / Home Improvement'), ('grocery', 'Grocery'), ('convenience', 'Convenience Store'), ('restaurant', 'Restaurant / QSR'), ('retail', 'General Retail'), ('pharmacy', 'Pharmacy'), ('automotive', 'Automotive'), ('fitness', 'Fitness / Gym'), ('hospitality', 'Hospitality / Hotel'), ('discount', 'Discount / Variety'), ('other', 'Other')], default='retail', max_length=30),
        ),
    ]
