# Generated by Django 5.1.15 on 2026-02-19 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0018_add_discount_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='walks.selfassessment'),
        ),
    ]
