# Generated by Django 5.1.15 on 2026-02-19 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0019_add_assessment_to_actionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='assessment_removed',
            field=models.BooleanField(default=False, help_text='Set to True when the linked assessment is deleted, to show indicator.'),
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_items', to='walks.selfassessment'),
        ),
    ]
