# Generated by Django 5.1.15 on 2026-02-19 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0020_actionitem_assessment_orphan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsubmission',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='reviewer_notes',
            field=models.TextField(blank=True, default='', help_text='Optional commentary from the reviewer.'),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='reviewer_rating',
            field=models.CharField(blank=True, choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='', help_text='Optional override rating set by the reviewer.', max_length=10),
        ),
    ]
