# Generated by Django 5.1.15 on 2026-02-19 18:45

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0021_submission_reviewer_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsubmission',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assessmentsubmission',
            name='image',
            field=models.FileField(upload_to=apps.core.storage.assessment_photo_path),
        ),
    ]
