# Generated by Django 5.1.15 on 2026-02-19 19:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_supportticket_source_external_id_nullable'),
        ('walks', '0022_assessment_video_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='review_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_action_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('dismissed', 'Dismissed')], default='open', max_length=20),
        ),
        migrations.CreateModel(
            name='ActionItemEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('status_changed', 'Status Changed'), ('response_added', 'Response Added'), ('photo_uploaded', 'Photo Uploaded'), ('ai_verified', 'AI Verified'), ('submitted_for_review', 'Submitted for Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('old_status', models.CharField(blank=True, default='', max_length=20)),
                ('new_status', models.CharField(blank=True, default='', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('action_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='walks.actionitem')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.organization')),
            ],
            options={
                'db_table': 'walks_actionitemevent',
                'ordering': ['created_at'],
            },
        ),
    ]
