# Generated by Django 5.1.15 on 2026-02-20 03:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_supportticket_source_external_id_nullable'),
        ('stores', '0015_orgsettings_location_enforcement'),
        ('walks', '0025_quick_assessment_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='selfassessment',
            name='suggestions_reviewed',
            field=models.BooleanField(default=False, help_text='True once the user has accepted/dismissed all AI suggestions.'),
        ),
        migrations.CreateModel(
            name='DismissedSuggestion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(help_text='The AI suggestion text.')),
                ('priority', models.CharField(blank=True, default='', max_length=10)),
                ('reason', models.CharField(blank=True, choices=[('not_relevant', 'Not Relevant'), ('already_handled', 'Already Handled'), ('low_priority', 'Low Priority'), ('other', 'Other')], default='', max_length=20)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissed_suggestions', to='walks.selfassessment')),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissed_suggestions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.organization')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissed_suggestions', to='stores.store')),
            ],
            options={
                'db_table': 'walks_dismissedsuggestion',
                'ordering': ['-created_at'],
            },
        ),
    ]
