# Generated by Django 5.1.15 on 2026-02-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_add_gamification_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='trial_source',
            field=models.CharField(blank=True, default='', help_text='Source of signup: product-tour, website, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='discount_percent',
            field=models.IntegerField(default=0, help_text='Volume discount percentage applied (0, 5, 10, 15, or 20).'),
        ),
    ]
