# Generated by Django 5.1.15 on 2026-02-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, default='', upload_to='apps.core.storage.org_file_path'),
        ),
    ]
