# Generated by Django 5.1.15 on 2026-02-17 14:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_membership_evaluator_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive organizations are disabled and cannot be accessed.'),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('store_count', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('demo_active', 'Demo Active'), ('converted', 'Converted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('demo_expires_at', models.DateTimeField(blank=True, help_text='When the demo access expires.', null=True)),
                ('source', models.CharField(default='website', help_text='Lead source: website, referral, etc.', max_length=50)),
                ('demo_org', models.ForeignKey(blank=True, help_text='The demo organization created for this lead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_leads', to='accounts.organization')),
            ],
            options={
                'db_table': 'accounts_lead',
                'ordering': ['-created_at'],
            },
        ),
    ]
