# Generated by Django 5.1.15 on 2026-02-18 15:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_organization_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='unsubscribed',
            field=models.BooleanField(default=False, help_text='Whether the lead has opted out of drip emails.'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.CreateModel(
            name='DripEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step', models.PositiveSmallIntegerField(help_text='Drip step number (0=welcome, 1=features, 2=roi, 3=free account).')),
                ('scheduled_at', models.DateTimeField(help_text='When this email should be sent.')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When this email was actually sent.', null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drip_emails', to='accounts.lead')),
            ],
            options={
                'db_table': 'accounts_drip_email',
                'ordering': ['scheduled_at'],
                'unique_together': {('lead', 'step')},
            },
        ),
    ]
