# Generated by Django 5.1.15 on 2026-02-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_supportticket_ticketmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('bug', 'Bug'), ('ui_feedback', 'UI Feedback'), ('enhancement', 'Enhancement Request'), ('question', 'Question'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='resolution_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
