# Generated by Django 5.1.15 on 2026-02-15 20:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_logo'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('integration_type', models.CharField(choices=[('manual', 'Manual Entry'), ('csv', 'CSV Import'), ('api', 'API Connection'), ('webhook', 'Webhook Receiver')], default='manual', max_length=20)),
                ('provider', models.CharField(choices=[('eagle', 'Eagle POS (Epicor)'), ('mango', 'Mango Report'), ('acenet', 'Acenet'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Connection config: API keys, endpoints, schedules, column mappings.')),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.organization')),
            ],
            options={
                'db_table': 'stores_integrationconfig',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StoreDataPoint',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric', models.CharField(db_index=True, help_text='Metric key: weekly_sales, transaction_count, oos_percentage, etc.', max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField(db_index=True)),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('csv_import', 'CSV Import'), ('eagle_api', 'Eagle API'), ('mango_import', 'Mango Import')], default='manual', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Raw data, import batch ID, notes, etc.')),
                ('integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_points', to='stores.integrationconfig')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='accounts.organization')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='stores.store')),
            ],
            options={
                'db_table': 'stores_storedatapoint',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['store', 'metric', 'date'], name='stores_stor_store_i_bfa476_idx')],
            },
        ),
    ]
