# Generated by Django 5.1.15 on 2026-02-16 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('stores', '0005_orgsettings_subscription_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='%(app_label)s_%(class)ss',
                to='accounts.organization',
            ),
        ),
    ]
