# Generated by Django 5.1.15 on 2026-02-17 14:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


def populate_unique_qr_tokens(apps, schema_editor):
    """Assign a unique UUID to each existing store."""
    Store = apps.get_model('stores', 'Store')
    for store in Store.objects.all():
        store.qr_verification_token = uuid.uuid4()
        store.save(update_fields=['qr_verification_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_organization_is_active_lead'),
        ('stores', '0007_store_latitude_store_longitude_store_manager_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='The responsible person for this region.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_regions', to='accounts.membership'),
        ),
        migrations.AddField(
            model_name='region',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent region for one-level nesting.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='stores.region'),
        ),
        # Step 1: Add qr_verification_token WITHOUT unique constraint
        migrations.AddField(
            model_name='store',
            name='qr_verification_token',
            field=models.UUIDField(default=uuid.uuid4, help_text='Token encoded in the store QR code for walk verification.'),
        ),
        # Step 2: Populate unique UUIDs for existing stores
        migrations.RunPython(populate_unique_qr_tokens, migrations.RunPython.noop),
        # Step 3: Now add the unique constraint
        migrations.AlterField(
            model_name='store',
            name='qr_verification_token',
            field=models.UUIDField(default=uuid.uuid4, help_text='Token encoded in the store QR code for walk verification.', unique=True),
        ),
        migrations.AddField(
            model_name='store',
            name='verification_method',
            field=models.CharField(choices=[('gps_only', 'GPS Only'), ('qr_only', 'QR Code Only'), ('gps_and_qr', 'GPS + QR (Both Required)'), ('either', 'GPS or QR (Either)')], default='gps_only', help_text='How location should be verified when starting a walk at this store.', max_length=20),
        ),
    ]
