# Generated by Django 5.1.15 on 2026-02-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_region_manager_region_parent_store_qr_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='color',
            field=models.CharField(blank=True, default='#3B82F6', help_text='Hex color code for map markers and UI (e.g. #3B82F6).', max_length=7),
        ),
    ]
