# Generated by Django 5.1.15 on 2026-02-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_region_color'),
        ('walks', '0015_departmenttype_scoringtemplate_source_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Departments available at this store.', related_name='stores', to='walks.department'),
        ),
    ]
