# Generated by Django 5.1.15 on 2026-02-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_achievement_plan_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsettings',
            name='action_item_deadline_critical',
            field=models.PositiveIntegerField(default=1, help_text='Default deadline in days for critical priority action items.'),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='action_item_deadline_high',
            field=models.PositiveIntegerField(default=3, help_text='Default deadline in days for high priority action items.'),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='action_item_deadline_low',
            field=models.PositiveIntegerField(default=14, help_text='Default deadline in days for low priority action items.'),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='action_item_deadline_medium',
            field=models.PositiveIntegerField(default=7, help_text='Default deadline in days for medium priority action items.'),
        ),
    ]
